/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PlayIndexImport } from './routes/play.index'
import { Route as PlayLeagueCodeImport } from './routes/play.$leagueCode'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlayIndexRoute = PlayIndexImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRoute,
} as any)

const PlayLeagueCodeRoute = PlayLeagueCodeImport.update({
  id: '/play/$leagueCode',
  path: '/play/$leagueCode',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/play/$leagueCode': {
      id: '/play/$leagueCode'
      path: '/play/$leagueCode'
      fullPath: '/play/$leagueCode'
      preLoaderRoute: typeof PlayLeagueCodeImport
      parentRoute: typeof rootRoute
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play/$leagueCode': typeof PlayLeagueCodeRoute
  '/play': typeof PlayIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play/$leagueCode': typeof PlayLeagueCodeRoute
  '/play': typeof PlayIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/play/$leagueCode': typeof PlayLeagueCodeRoute
  '/play/': typeof PlayIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/play/$leagueCode' | '/play'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/play/$leagueCode' | '/play'
  id: '__root__' | '/' | '/play/$leagueCode' | '/play/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayLeagueCodeRoute: typeof PlayLeagueCodeRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayLeagueCodeRoute: PlayLeagueCodeRoute,
  PlayIndexRoute: PlayIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/play/$leagueCode",
        "/play/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/play/$leagueCode": {
      "filePath": "play.$leagueCode.tsx"
    },
    "/play/": {
      "filePath": "play.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
