/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PlayIndexImport } from './routes/play.index'
import { Route as GamesIndexImport } from './routes/games.index'
import { Route as PlayLeagueCodeImport } from './routes/play.$leagueCode'
import { Route as GamesGameIdImport } from './routes/games.$gameId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlayIndexRoute = PlayIndexImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRoute,
} as any)

const GamesIndexRoute = GamesIndexImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRoute,
} as any)

const PlayLeagueCodeRoute = PlayLeagueCodeImport.update({
  id: '/play/$leagueCode',
  path: '/play/$leagueCode',
  getParentRoute: () => rootRoute,
} as any)

const GamesGameIdRoute = GamesGameIdImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdImport
      parentRoute: typeof rootRoute
    }
    '/play/$leagueCode': {
      id: '/play/$leagueCode'
      path: '/play/$leagueCode'
      fullPath: '/play/$leagueCode'
      preLoaderRoute: typeof PlayLeagueCodeImport
      parentRoute: typeof rootRoute
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexImport
      parentRoute: typeof rootRoute
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/play/$leagueCode': typeof PlayLeagueCodeRoute
  '/games': typeof GamesIndexRoute
  '/play': typeof PlayIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/play/$leagueCode': typeof PlayLeagueCodeRoute
  '/games': typeof GamesIndexRoute
  '/play': typeof PlayIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/play/$leagueCode': typeof PlayLeagueCodeRoute
  '/games/': typeof GamesIndexRoute
  '/play/': typeof PlayIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/$gameId' | '/play/$leagueCode' | '/games' | '/play'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/$gameId' | '/play/$leagueCode' | '/games' | '/play'
  id:
    | '__root__'
    | '/'
    | '/games/$gameId'
    | '/play/$leagueCode'
    | '/games/'
    | '/play/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  PlayLeagueCodeRoute: typeof PlayLeagueCodeRoute
  GamesIndexRoute: typeof GamesIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  PlayLeagueCodeRoute: PlayLeagueCodeRoute,
  GamesIndexRoute: GamesIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/games/$gameId",
        "/play/$leagueCode",
        "/games/",
        "/play/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/games/$gameId": {
      "filePath": "games.$gameId.tsx"
    },
    "/play/$leagueCode": {
      "filePath": "play.$leagueCode.tsx"
    },
    "/games/": {
      "filePath": "games.index.tsx"
    },
    "/play/": {
      "filePath": "play.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
